[build]
  builder = "dockerfile"
  
[[mounts]]
  mountPath = "/data"
  volumeName = "irc-rag-data"

[environments.production]
  PORT = "8000"
  RAILWAY_ENVIRONMENT = "production"
  
[environments.staging]
  PORT = "8000"
  RAILWAY_ENVIRONMENT = "staging"
